#!/bin/bash
#set -e

BDIR=`pwd`/github

_exec() {
   local arr=("$@")
   for o in "${arr[@]}"; do
      echo -e "\e[1;33m$ $o\e[0m"
      eval "$o"
      echo
   done
}


cq=()
while read f; do

   IFS='=' read -ra a1 <<< "$f"
   [[ ${a1[0]} == '' ]] && continue
   [[ ${a1[0]:0:1} == '#' ]] && continue

   GIT=${a1[1]}
   DIR=${BDIR}/${a1[0]}

   [[ ! -d ${DIR} ]] && {
      cq+=("mkdir -p ${DIR}")
      cq+=("git clone ${GIT} ${DIR}")
   }
   [[ -d ${DIR} ]] && {
      cq+=("cd ${DIR}; git pull")
   }

done <<< `cat .etc/github`

echo

_exec "${cq[@]}"
