#!/bin/bash
#set -e


declare -a cq

[[ ! -f .env ]] && {
   [[ ! -f .env-bak ]] && {
      echo '.env not found !!!'
      echo
      exit;
   }

   cp .env-bak .env
}

source .env

USER='0:0'
[[ -z $VERSION ]] && VERSION='1.0.0'
[[ -z $VERCODE ]] && VERCODE=`git rev-list HEAD --count`
[[ -z $VERCODE ]] && VERCODE=1
[[ -z $ORGAN ]] && ORGAN=dev
VERPREV=$(( VERCODE - 1 ))
VERSION=${VERSION%.*}.${VERCODE}

[[ -z $MACH ]] && MACH=`uname -i`
case $MACH in
x86_64|amd64)
   MACH='amd64'
   DMACH='amd64'
   ;;

arm64|arm64v8|aarch64)
   MACH='arm64'
   DMACH='arm64v8'
   ;;
esac

DFILE=docker/Dockerfile
FROM=`cat ${DFILE} | grep FROM | cut -d' ' -f2`

_exec() {
   local arr=("$@")
   for o in "${arr[@]}"; do
      echo -e "\e[1;33m$ $o\e[0m"
      eval "$o"
      echo
   done
}

_exec_display() {
   local arr=("$@")
   for o in "${arr[@]}"; do
      echo -e "\e[1;33m$ $o\e[0m"
      echo
   done
}

_terms() {
   rc=`docker ps --filter status=running --format "{{.Names}}" | grep "${NAME}" | wc -l`

   [[ -z $ARCH ]] && ARCH='latest'

   local cc=()
   [[ $rc == '0' ]] && {
      cc+=("docker run -it --rm --user=${USER} --name ${NAME} ${OPTION} ${ORGAN}/${NAME}:${ARCH} $SHELL")
   }
   [[ $rc != '0' ]] && {
      cc+=("docker exec -it --user=${USER} ${NAME} $SHELL")
   }

   _exec "${cc[@]}"
}


## Text Color
# Reset
Color_Off='\e[0m'       # Text Reset

# Regular Colors
Black='\e[0;30m'        # Black
Red='\e[0;31m'          # Red
Green='\e[0;32m'        # Green
Yellow='\e[0;33m'       # Yellow
Blue='\e[0;34m'         # Blue
Purple='\e[0;35m'       # Purple
Cyan='\e[0;36m'         # Cyan
White='\e[0;37m'        # White

# Bold
BBlack='\e[1;30m'       # Black
BRed='\e[1;31m'         # Red
BGreen='\e[1;32m'       # Green
BYellow='\e[1;33m'      # Yellow
BBlue='\e[1;34m'        # Blue
BPurple='\e[1;35m'      # Purple
BCyan='\e[1;36m'        # Cyan
BWhite='\e[1;37m'       # White

# Underline
UBlack='\e[4;30m'       # Black
URed='\e[4;31m'         # Red
UGreen='\e[4;32m'       # Green
UYellow='\e[4;33m'      # Yellow
UBlue='\e[4;34m'        # Blue
UPurple='\e[4;35m'      # Purple
UCyan='\e[4;36m'        # Cyan
UWhite='\e[4;37m'       # White

# Background
On_Black='\e[40m'       # Black
On_Red='\e[41m'         # Red
On_Green='\e[42m'       # Green
On_Yellow='\e[43m'      # Yellow
On_Blue='\e[44m'        # Blue
On_Purple='\e[45m'      # Purple
On_Cyan='\e[46m'        # Cyan
On_White='\e[47m'       # White

# High Intensity
IBlack='\e[0;90m'       # Black
IRed='\e[0;91m'         # Red
IGreen='\e[0;92m'       # Green
IYellow='\e[0;93m'      # Yellow
IBlue='\e[0;94m'        # Blue
IPurple='\e[0;95m'      # Purple
ICyan='\e[0;96m'        # Cyan
IWhite='\e[0;97m'       # White

# Bold High Intensity
BIBlack='\e[1;90m'      # Black
BIRed='\e[1;91m'        # Red
BIGreen='\e[1;92m'      # Green
BIYellow='\e[1;93m'     # Yellow
BIBlue='\e[1;94m'       # Blue
BIPurple='\e[1;95m'     # Purple
BICyan='\e[1;96m'       # Cyan
BIWhite='\e[1;97m'      # White

# High Intensity backgrounds
On_IBlack='\e[0;100m'   # Black
On_IRed='\e[0;101m'     # Red
On_IGreen='\e[0;102m'   # Green
On_IYellow='\e[0;103m'  # Yellow
On_IBlue='\e[0;104m'    # Blue
On_IPurple='\e[0;105m'  # Purple
On_ICyan='\e[0;106m'    # Cyan
On_IWhite='\e[0;107m'   # White
